# Imagem base do Node para o ambiente de desenvolvimento
FROM node:20-alpine

# Define o diretório de trabalho
WORKDIR /app

# Copia os arquivos de definição de pacotes
COPY package.json package-lock.json ./

# Instala as dependências. O `npm ci` é geralmente mais rápido e seguro para CI/CD e builds.
RUN npm ci

# Copia o restante do código-fonte da aplicação
COPY . .
